server: 
  port: 6000

spring:
  application:
    name: service-zull
eureka:
  client:
    service-url: 
      defaultZone: http://eureka9003.com:9003/eureka/,http://eureka9002.com:9002/eureka/,http://eureka9001.com:9001/eureka/
  instance: 
    instance-id: service-zull6000                        #自定义服务名称信息
    prefer-ip-address: true                                   #访问路径可以显示IP地址
zuul:
  prefix: /MyDemo                             #代理名成之前增加前缀
  ignored-services: service-provider-hystrix           #此配置是禁止使用服务名请求
  routes:
    mydept.serviceId: service-provider-hystrix
    mydept.path: /king/**          #访问地址修改服务名为代理名称King
info: 
  app.name: service-zull
  company.name: this is zull program
  build.artifactId: $project.artifactId$
  build.version: $project.version$
