spring:
  application:
    name: service-eureka
eureka:
  instance:
    hostname: eureka9003.com
  client:
    service-url:
      #defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
      defaultZone: http://eureka9001.com:9001/eureka/,http://eureka9002.com:9002/eureka/     
server:
  port: 9003
