server:
  port: 5000
spring:
  application:
    name: service-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/king-guest/service-config.git
          
    
  