 spring:
  application:
    name: service-eureka
 eureka:
  instance:
    hostname: eureka9001.com
  client:
    service-url:
      #defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/        #设置与Eureka Server交互的地址查询服务和注册服务都需要依赖这个地址。
      defaultZone: http://eureka9003.com:9003/eureka/,http://eureka9002.com:9002/eureka/
 server:
   port: 9001
